#!/usr/bin/env python3
"""Capture real move-to-front traffic from a pyflate decode and emit
stimulus + golden vectors for the Verilog testbench.

pyflate calls move_to_front from two places: compute_selectors_list (a short
table of Huffman group selectors) and decode_huffman_block (the 'favourites'
symbol table, which is the hot one). Only the busiest table is captured -- that
is the one the accelerator replaces.
"""
import importlib.util, os, sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.environ.get("PYFLATE_SRC", os.path.join(HERE, "pyflate_orig.py"))
DATA = os.environ.get("PYFLATE_DATA", os.path.join(HERE, "interpreter.tar.bz2"))
MAX  = int(os.environ.get("MAX_VECTORS", "200000"))

spec = importlib.util.spec_from_file_location("pyflate_ref", SRC)
m = importlib.util.module_from_spec(spec); sys.modules[spec.name] = m
spec.loader.exec_module(m)

def as_int(x):
    return x if isinstance(x, int) else x[0]

traces = defaultdict(list)    # id(list) -> [(index, promoted_value)]
tables = {}                   # id(list) -> initial contents

_orig = m.move_to_front
def traced(l, c):
    k = id(l)
    if k not in tables:
        tables[k] = [as_int(v) for v in l]
    traces[k].append((c, as_int(l[c])))
    return _orig(l, c)
m.move_to_front = traced

with open(DATA, "rb") as fp:
    field = m.RBitfield(fp)
    assert field.readbits(16) == 0x425a, "not a bzip2 stream"
    m.bzip2_main(field)

assert traces, "no move_to_front calls captured"
print("move_to_front call sites seen:")
for k, t in sorted(traces.items(), key=lambda kv: -len(kv[1])):
    print(f"   table of {len(tables[k]):3d} entries : {len(t):7d} calls")

hot = max(traces, key=lambda k: len(traces[k]))
table, trace = tables[hot], traces[hot][:MAX]
tlen = len(table)

with open(os.path.join(HERE, "stim_table.hex"), "w") as f:
    for v in table:
        f.write("%02x\n" % v)
with open(os.path.join(HERE, "stim_vectors.hex"), "w") as f:
    for idx, out in trace:
        f.write("%02x %02x\n" % (idx, out))
with open(os.path.join(HERE, "stim_params.vh"), "w") as f:
    f.write("// generated by gen_stimulus.py -- do not edit\n")
    f.write("`define STIM_TABLE_LEN %d\n" % tlen)
    f.write("`define STIM_NUM_VECTORS %d\n" % len(trace))

print(f"\nselected the hot table: {tlen} entries, {len(trace)} vectors captured")
print(f"   distinct indices : {len({i for i,_ in trace})} (max {max(i for i,_ in trace)})")
print(f"   index 0 fraction : {sum(1 for i,_ in trace if i==0)/len(trace)*100:.1f}%")
print("wrote stim_table.hex, stim_vectors.hex, stim_params.vh")
